language: python

python:
  - 2.7
  - 3.6
  - 3.7-dev

services:
  - docker

cache: pip

branches:
  only:
    - master

install:
  - pip install -r requirements.txt

script:
  - .travis/docker-deploy.sh
