language: python

python:
  - 2.7
  - 3.7
  - 3.7-dev

services:
  - docker

install:
  - pip install -r requirements.txt

deploy:
  provider: script
  script: scripts/deploy-docker.sh
  on:
    branch: master