dist: bionic
language: python

python:
    - '3.7'
    - '3.8'
    - 'nightly'

services:
  - docker

script:
  - if [[ -z "$IMAGE_TAG" ]]; then exit 1; fi
  - docker build -t $IMAGE_TAG .

deploy:
  provider: script
  script: .travis/docker-push.sh
  on:
    branch: master
